### ISSUE TITLE
gwf: creating IC package very slow (version 0.6.1)

### ISSUE THREAD

**Issue by RdWitte** [gwmod/nlmod#262]
Hi All,

Since I've updated nlmod from 0.5.3 to 0.6.1 the progress of creating the IC package has become very slow (ca. 6-8 min vs a few seconds). I have tried presenting different sets of initial heads (i.e. all 1's, or the actual initial heads), but the outcome is the same.
Although I don't really see what changes from 0.5.3 to 0.6.1 could have an impact on this, I was wondering if anyone else has encountered issues with this?

Issue occurs during:
gwf = nlmod.gwf.ds_to_gwf(ds)

![image](https://github.com/ArtesiaWater/nlmod/assets/127938163/65fa8eb7-5529-4e2e-9447-f23befdc3ab7)

**Comment by dbrakenhoff** [comment]
Thanks for posting this issue. I'm not sure but this might have to do with passing a DataArray to flopy instead of the actual underlying numpy array. We've run into bizarrely bad performance before related to that issue. 

Does this issue also occur with one of the example notebooks? And can you post the versions of xarray, numpy and flopy for us?

**Comment by RdWitte** [comment]
I ran the IJmuiden notebook, results:
0.5.3 -> IC loading time ~14 sec.
0.6.1 -> IC loading time <<1 sec.

- 0.5.3: 
Bottleneck==1.3.5
contextily==1.2.0
flopy==3.3.6
geopandas==0.12.1
geopy==2.3.0
hydropandas==0.8.0
imod==0.11.4
matplotlib==3.6.2
nlmod==0.5.3
numpy==1.23.4
pandas==1.5.3
Shapely==2.0.1
openpyxl==3.0.10
geocube==0.4.2
rioxarray==0.12.4

- 0.6.1: 
Bottleneck==1.3.5
contextily==1.3.0
flopy==3.3.6
geopandas==0.12.1
geopy==2.3.0
hydropandas==0.8.0
imod==0.14.1
matplotlib==3.6.2
nlmod==0.6.1
numpy==1.23.4
pandas==1.5.3
Shapely==2.0.1
geocube==0.4.2
openpyxl==3.1.2
rioxarray==0.15.0

**Comment by dbrakenhoff** [comment]
This issue has been fixed in the dev branch (#200). It's what I mentioned before. When a DataArray is passed to flopy, performance becomes extremely slow. In the lastest version of nlmod we ensure all data from the model dataset is passed to flopy as numpy arrays. 

For now there are two workarounds:
- Update nlmod to the develop version `pip install git+https://github.com/ArtesiaWater/nlmod.git@dev`
- Pass the starting heads to the IC package as a numpy array. 

I'll check with the rest whether we can create a new release soon to address this issue.

**Comment by dbrakenhoff** [comment]
Fixed by new release v0.7.0, closing issue.
