### ISSUE TITLE
Split layer names and Regis legend

### ISSUE THREAD

**Issue by vincentpost** [gwmod/nlmod#364]
The function split_layers_ds in nlmod.layers.py appends _n to REGIS layers that are subdivided into multiple sublayers (starting at _1, BTW why not _0 since Python is zero-based ;-)). This breaks the ability to directly use the dictionary created by get_legend from nlmod.read.regis.py when plotting a DatasetCrossSection.

Suggested fix: replace line 184 in nlmod.plot.dcs.py:

colors = [colors[layer] for layer in self.layer]

with:

colors = [colors[layer.split('_')[0]] for layer in self.layer]

**Comment by dbrakenhoff** [comment]
Good suggestions @vincentpost!

The 1 as first index is something of a mystery. No idea why I did that. And I like your suggestion for the colors. I'll submit a PR for both.

**Comment by dbrakenhoff** [comment]
The dev branch contains these changes!

**Comment by vincentpost** [comment]
Great, thanks Davíd!

**Comment by rubencalje** [comment]
I was responsible for the +1 in the layer names. I chose this because these layer names are displayed in cross-sections and tables that people may use in their reports (so outside of the Python-world). On top of that, the counting of sandy or clayey REGIS layers also start at 1 (`BXz1`, `BXz2`, `BXz3`).

So when you split the first sandy layer of the formation of Boxtel (`BXz1`), I think it's prettier that you get `BXz1_1 `and `BXz1_2`, instead of `BXz1_0` and `BXz1_1`.

I am therefore in favor of reverting this change. It has not been implemented in a released version jet. I will add a pull request with this proposal.

**Comment by rubencalje** [comment]
Hi @vincentpost, I reverted the change to start counting at 0 by default when splitting layers. However, now you can use `nlmod.layers.split_layers_ds(start_suffix_at=0)`, if you really want to start counting at 0.

**Comment by vincentpost** [comment]
Hi @rubencalje ,

That is a very nice compromise. I can follow your reasoning, for consistency with REGIS the user will find it more intuitive to start counting at 1. I was taking the developer perspective.
